//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzYuzu.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EzYuzu.Properties.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Install.
        /// </summary>
        internal static string ButtonProcessNewInstall {
            get {
                return ResourceManager.GetString("ButtonProcessNewInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the Directory containing Yuzu.exe.
        /// </summary>
        internal static string ButtonProcessSelectYuzuLocation {
            get {
                return ResourceManager.GetString("ButtonProcessSelectYuzuLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Yuzu.
        /// </summary>
        internal static string ButtonProcessUpdateYuzu {
            get {
                return ResourceManager.GetString("ButtonProcessUpdateYuzu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yuzu is currently Up-To-Date!.
        /// </summary>
        internal static string ButtonProcessYuzuUpToDate {
            get {
                return ResourceManager.GetString("ButtonProcessYuzuUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Early Access.
        /// </summary>
        internal static string ComboBoxUpdateChannelEarlyAccess {
            get {
                return ResourceManager.GetString("ComboBoxUpdateChannelEarlyAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mainline.
        /// </summary>
        internal static string ComboBoxUpdateChannelMainline {
            get {
                return ResourceManager.GetString("ComboBoxUpdateChannelMainline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse to the folder containing yuzu.exe.
        /// </summary>
        internal static string FolderBrowserTitle {
            get {
                return ResourceManager.GetString("FolderBrowserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string FormAboutTitle {
            get {
                return ResourceManager.GetString("FormAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EzYuzu - Yuzu Portable Updater.
        /// </summary>
        internal static string FormMainTitle {
            get {
                return ResourceManager.GetString("FormMainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Channel:.
        /// </summary>
        internal static string LabelUpdateChannel {
            get {
                return ResourceManager.GetString("LabelUpdateChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Channel (Auto-Detected):.
        /// </summary>
        internal static string LabelUpdateChannelAutoDetected {
            get {
                return ResourceManager.GetString("LabelUpdateChannelAutoDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string LabelVersion {
            get {
                return ResourceManager.GetString("LabelVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse to Yuzu.exe Folder Location:.
        /// </summary>
        internal static string LabelYuzuLocation {
            get {
                return ResourceManager.GetString("LabelYuzuLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please browse and select your Yuzu.exe folder location first.
        /// </summary>
        internal static string MessageBoxNoPathSelected {
            get {
                return ResourceManager.GetString("MessageBoxNoPathSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Yuzu install prevented with prevent-new flag..
        /// </summary>
        internal static string ProcessPreventNewInstall {
            get {
                return ResourceManager.GetString("ProcessPreventNewInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided Yuzu folder is not a valid directory.
        /// </summary>
        internal static string ProcessYuzuLocationInvalid {
            get {
                return ResourceManager.GetString("ProcessYuzuLocationInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EzYuzu
        ///Yuzu Portable Updater (Unofficial) by amakvana
        ///
        ///https://github.com/amakvana/EzYuzu
        ///
        ///This software is licensed under GNU GPL-3.0
        ///Source code is available in repository above
        ///
        ///Credits: https://github.com/amakvana/EzYuzu#acknowledgements
        ///
        ///Disclaimer:
        ///This software comes with no warranty, express or implied nor does the author makes no representation of warranties. The author claims no responsibility for damages resulting from any use or misuse of the software..
        /// </summary>
        internal static string TextBoxAboutDescription {
            get {
                return ResourceManager.GetString("TextBoxAboutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string ToolStripAbout {
            get {
                return ResourceManager.GetString("ToolStripAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates.
        /// </summary>
        internal static string ToolStripCheckForUpdates {
            get {
                return ResourceManager.GetString("ToolStripCheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string ToolStripExit {
            get {
                return ResourceManager.GetString("ToolStripExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string ToolStripFile {
            get {
                return ResourceManager.GetString("ToolStripFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string ToolStripGeneral {
            get {
                return ResourceManager.GetString("ToolStripGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string ToolStripHelp {
            get {
                return ResourceManager.GetString("ToolStripHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string ToolStripOptions {
            get {
                return ResourceManager.GetString("ToolStripOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override Update Channel.
        /// </summary>
        internal static string ToolStripOverrideUpdateChannel {
            get {
                return ResourceManager.GetString("ToolStripOverrideUpdateChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinstall Visual C++.
        /// </summary>
        internal static string ToolStripReinstallVisualC {
            get {
                return ResourceManager.GetString("ToolStripReinstallVisualC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Channel.
        /// </summary>
        internal static string ToolStripUpdateChannel {
            get {
                return ResourceManager.GetString("ToolStripUpdateChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Yuzu.
        /// </summary>
        internal static string ToolStripUpdateYuzu {
            get {
                return ResourceManager.GetString("ToolStripUpdateYuzu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yuzu Website.
        /// </summary>
        internal static string ToolStripYuzuWebsite {
            get {
                return ResourceManager.GetString("ToolStripYuzuWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yuzu not detected, click to download a fresh copy of Yuzu.
        /// </summary>
        internal static string ToolTipButtonProcessNewInstall {
            get {
                return ResourceManager.GetString("ToolTipButtonProcessNewInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to download the latest version of Yuzu.
        /// </summary>
        internal static string ToolTipButtonProcessUpdateYuzu {
            get {
                return ResourceManager.GetString("ToolTipButtonProcessUpdateYuzu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The latest version of Yuzu is currently installed.
        /// </summary>
        internal static string ToolTipButtonProcessYuzuUpToDate {
            get {
                return ResourceManager.GetString("ToolTipButtonProcessYuzuUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress completed of current action.
        /// </summary>
        internal static string ToolTipCurrentProgress {
            get {
                return ResourceManager.GetString("ToolTipCurrentProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current Update Channel of Yuzu. Auto-detected when the Yuzu Path is selected.
        ///Can be manually overridden by going into Options &gt; General &gt; Update Channel &gt; Override Update Channel.
        ///
        ///Mainline - Contains all regular daily Yuzu updates. More stable.
        ///Early Access - Contains the latest experimental features and fixes, before they are merged into Mainline builds. Less stable.
        ///
        ///When no channel is detected, EzYuzu defaults to Mainline..
        /// </summary>
        internal static string ToolTipUpdateChannel {
            get {
                return ResourceManager.GetString("ToolTipUpdateChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click and browse to your Yuzu.exe Folder Location.
        /// </summary>
        internal static string ToolTipYuzuLocation {
            get {
                return ResourceManager.GetString("ToolTipYuzuLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version of EzYuzu available, please download from https://github.com/amakvana/EzYuzu.
        /// </summary>
        internal static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You currently have the latest version of EzYuzu.
        /// </summary>
        internal static string UpdateLatestVersion {
            get {
                return ResourceManager.GetString("UpdateLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This version of EzYuzu is no longer supported, please download the latest version from https://github.com/amakvana/EzYuzu.
        /// </summary>
        internal static string UpdateNotSupported {
            get {
                return ResourceManager.GetString("UpdateNotSupported", resourceCulture);
            }
        }
    }
}
